### PR TITLE
Unified addTestDevice - no fill error

### LINKED ISSUE #34: Error: No fill
Based on another issue submitted (https://github.com/callstack-io/react-native-fbads/issues/24), this seems to be because an ad request hasn't been sent.  I'm assuming this is only because I haven't sent a request with a real device and I'm just testing.  According to the documentation, "When you run app on simulator,  it automatically gets added. [as a test device]"  It seems like it's not getting added as a test device.

Any help is appreciated.

```
Error: No fill
    at createErrorFromErrorData (NativeModules.js:116)
    at NativeModules.js:79
    at MessageQueue.__invokeCallback (MessageQueue.js:276)
    at MessageQueue.js:127
    at guard (MessageQueue.js:46)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:71
```

### PR DESCRIPTION
**Pull request by jakubsta**
This PR resolve #34.
After adding `[FBAdSettings addTestDevice:[FBAdSettings testDeviceHash]];` I eventually was able to display ads on iOS simulator. Previously I always got `1001 no fill` error.
Unfortunately, Android SDK does not have `testDeviceHash` method so I had to check how `AdSettings` works from decompiled code.

### CODE REVIEW

**Comment by grabbou** [comment]
Great! We did the same in Exponent.

CC: @satya164

File: src/ios/CTKAdSettingsManager.m [hunk 1]
```diff
@@ -28,8 +28,8 @@ @implementation CTKAdSettingsManager
 
 RCT_EXPORT_MODULE()
 
-RCT_EXPORT_METHOD(addTestDevice:(NSString *)deviceHash) {
-  [FBAdSettings addTestDevice:deviceHash];
+RCT_EXPORT_METHOD(addTestDevice) {
+  [FBAdSettings addTestDevice:[FBAdSettings testDeviceHash]];
```
Comment (grabbou) [inline src/ios/CTKAdSettingsManager.m]: Can we use `constantsToExport` to export `deviceHash` and make `addTestDevice` accept any string, rather than implicitly using own device hash when argument is undefined?

File: src/android/src/main/java/io/callstack/react/fbads/AdSettingsManager.java [hunk 2]
```diff
@@ -25,8 +31,12 @@ public String getName() {
     }
 
     @ReactMethod
-    public void addTestDevice(String deviceHash) {
-        AdSettings.addTestDevice(deviceHash);
+    public void addTestDevice() {
+        SharedPreferences sp = context.getSharedPreferences("FBAdPrefs", 0);
```
Comment (satya164) [inline src/android/src/main/java/io/callstack/react/fbads/AdSettingsManager.java]: Why not just `getReactApplicationContext().getSharedPreferences("FBAdPrefs", 0);` instead of saving context in variable?

File: Readme.md [hunk 3]
```diff
@@ -251,14 +251,13 @@ AdSettings contains global settings for all ad controls.
...
-debug log.
+Registers device to receive test ads. When you run app on simulator, it should automatically get added. Use it
+to receive test ads in development mode on a standalone phone.
 
-All devices should be specified before any other action takes place, like [`AdsManager`](#nativeadsmanager) gets created.
+Should be called before any other action takes place, like [`AdsManager`](#nativeadsmanager) gets created.
 
 ```js
-AdSettings.addTestDevice('hash');
+AdSettings.addTestDevice();
```
Comment (satya164) [inline Readme.md]: The method name feels wrong now, because it doesn't add a test device now, it adds the current device as test device.

**Comment by jakubsta** [comment]
@grabbou @satya164 I've just pushed fixes.

File: Readme.md [hunk 4]
```diff
@@ -249,11 +250,15 @@ import { AdSettings } from 'react-native-fbads';
 
 AdSettings contains global settings for all ad controls.
 
+#### deviceHashedId
```
Comment (satya164) [inline Readme.md]: Imo it should just be `deviceHash`, or maybe `currentDeviceHash` to denote that it's hash for current device.

Comment (jakubsta) [inline Readme.md]: Not sure. I also was surprised by this name but in audience sdk they really called this [`hashed id`](https://developers.facebook.com/docs/audience-network/testing)

Comment (satya164) [inline Readme.md]: @jakubsta they are certainly not consistent because they also call it `deviceIdHash` and `testDeviceHash`. `deviceHashedId` looks like something where I'd easily make typos.

Comment (jakubsta) [inline Readme.md]: You're right, maybe it does not have much sense to try to be consistent with their names.

Will change to `currentDeviceHash `.

File: Readme.md [hunk 5]
```diff
@@ -249,11 +250,15 @@ import { AdSettings } from 'react-native-fbads';
...
+
+Constant which contains current device's hash id.
+
 #### addTestDevice
 
-Registers given device to receive test ads. When you run app on simulator, it automatically gets added. Use it
+Registers given device to receive test ads. When you run app on simulator, it should automatically get added. Use it
 to receive test ads in development mode on a standalone phone. Hash of the current device can be obtained from a
-debug log.
+debug log or `AdSettings.deviceHashedId` constant.
```
Comment (satya164) [inline Readme.md]: Need to update this too

**Comment by booboothefool** [comment]
Is this why I'm not seeing ads on iOS? https://github.com/callstack-io/react-native-fbads/issues/45#issuecomment-283134703

How do I get this to work on 3.1.1 (I'm using React Native 0.37).

**Comment by grabbou** [comment]
Yes, @booboothefool, that was the reason. Should be gone when we release a new version.
